#!/usr/bin/env bash
# install haproxy load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
sudo chown -R "$USER:$USER" /etc/haproxy
str="
listen firstbalance
        bind *:80
        balance roundrobin
        server 292-web-01 35.231.46.174:80 check
        server 292-web-02 35.185.29.97:80 check"
echo "$str" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
sudo service haproxy restart
