#!/usr/bin/env bash
# fix nginx web server
pkill -9 nginx
sed -i "s/4/1/" /etc/nginx/nginx.conf
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
service nginx restart
